package com.anatame.webviewajax

data class BlockHosts(
    val hosts: List<String> = listOf<String>(
        "absolutionbravery.com",
        "addthis.com",
        "s7.addthis.com",
        "amung.us",
        "whos.amung.us",
        "onesignal.com",
        "cdn.onesignal.com",
        "xmllover.com",
        "googletagmanager.com",
        "www.googletagmanager.com",
        "google-analytics.com",
        "www.google-analytics.com",
        "connect.facebook.net",
        "disqus.com",
        "referrer.disqus.com",
        "offerimage.com",
        "s1.bunnycdn.ru",
        "dacmaiss.com",
        "s7.addthis.com",
//    "cdn.heycdn41.xyz",
       "     cdn.trell.co",
//        "www.gstatic.com",
        "untimburra.com"
    )
)

//"absolutionbravery.com",
//"addthis.com",
//"s7.addthis.com",
//"ajax.googleapis.com",
//"amung.us",
//"whos.amung.us",
//"bunnycdn.ru",
//"s1.bunnycdn.ru",
//"static.bunnycdn.ru",
//"cloudflare.com",
//"cdnjs.cloudflare.com",
//"disqus.com",
//"fmoviescomment.disqus.com",
//"referrer.disqus.com",
//"realtime.services.disqus.com",
//"disquscdn.com",
//"a.disquscdn.com",
//"c.disquscdn.com",
//"facebook.com",
//"www.facebook.com",
//"facebook.net",
//"connect.facebook.net",
//"fmovies.to",
//"fonts.googleapis.com",
//"google-analytics.com",
//"www.google-analytics.com",
//"google.com",
//"accounts.google.com",
//"apis.google.com",
//"www.google.com",
//"googletagmanager.com",
//"www.googletagmanager.com",
//"gstatic.com",
//"ssl.gstatic.com",
//"www.gstatic.com",
//"mcloud.to",
//"vwko.mcloud.to",
//"onesignal.com",
//"cdn.onesignal.com",
//"xmllover.com",